app/routes.py
from flask import render_template, request, redirect, url_for, Blueprint, session, flash, current_app, jsonify
from .modules.user_mgt_module.student import Student
from .modules.login_register_module import Authorization
from .modules.reservation_module.reserve_lab import Reservation
from datetime import datetime
import os
from werkzeug.utils import secure_filename


# Register as a Blueprint for create_app() function to recognize as Flask app
main = Blueprint('main', __name__, template_folder='templates/student')

# Allowed extensions
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

# Initialize Authorization instance Login Register Module
auth = Authorization()

# Initialize Reservation instance
reservation = Reservation()

student = None # Global student object to be reusable

# Function to check if the file extension is valid
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@main.after_request
def after_request(response):
    response.headers['Cache-Control'] = 'no-cache,no-store,must-revalidate'
    return response 

@main.route('/')
def index():
    """Landing page."""
    return render_template(
                            'index.html',
                            user_in_login_page=False, 
                            action='Login'
                            )

@main.route('/login')
def login():
    """Login page."""
    return render_template(
                            'login.html',
                            user_in_login_page=True,
                            action='Back'
                           )


@main.route('/dashboard')
def dashboard():
    """Dashboard page."""
    global student
    try:

        if session.get('student') is not None:
            if student is None:
                student_data = session.get('student')
                student = Student(**student_data)
            return render_template(
                                    'dashboard.html', 
                                    student=student,
                                    user_in_login_page=True,
                                    action='Logout',
                                   )
         
        else:
            message = "Please login first."
            flash(message)
            return redirect(url_for('main.login'))
        
    except Exception as e:
        flash(str(e),'error')
        flash("Please try again")
        #session['student'] = None
        return redirect(url_for('main.login'))
    
@main.route('/leaderboards')
def leaderboards():
    """Render leaderboards"""
    """Dashboard page."""
    global student
    try:
        update_date = datetime.today().strftime('%B %d, %Y')

        if session.get('student') is not None:
            if student is None:
                student_data = session.get('student')
                student = Student(**student_data)
            return render_template(
                                    'leaderboards.html', 
                                    student=student,
                                    user_in_login_page=True,
                                    action='Logout',
                                    update_date= update_date
                                   )
         
        else:
            message = "Please login first."
            flash(message)
            return redirect(url_for('main.login'))
        
    except Exception as e:
        flash(str(e),'error')
        flash("Please try again")
        #session['student'] = None
        return redirect(url_for('main.login'))



@main.route('/announcements')
def announcements():
    """Announcements page."""
    global student
    try:

        if session.get('student') is not None:
            if student is None:
                student_data = session.get('student')
                student = Student(**student_data)
                
            response = student.retrieve_all_announcements()
            print(announcements)
            return render_template(
                                    'announcements.html', 
                                    student=student,
                                    user_in_login_page=True,
                                    action='Logout',
                                   )
         
        else:
            message = "Please login first."
            flash(message)
            return redirect(url_for('main.login'))
        
    except Exception as e:
        flash(str(e),'error')
        flash("Please try again")
        #session['student'] = None
        return redirect(url_for('main.login'))


@main.route('/sitin')
def sitin():
    """Render Sit-in page."""
    global student

    datenow = datetime.now()

    if not session.get('student') == None:
        if not student:
            student_data = session.get('student')
            student = Student(**student_data)

        return render_template(
                                'sitin.html', 
                                student=student,
                                user_in_login_page=True,
                                action='Logout',
                                datenow=datenow
                               )
    else:
        message = "Please login first."
        flash(message)
        return redirect(url_for('main.login'))


@main.route('/reserve')
def reserve():
    """Reserve page."""
    global student
    try:

        if not session['student'] == None:
            if student == None:
                student_data = session.get('student')
                student = Student(**student_data)
            
            labs = reservation.retrieve_labs()

            return render_template(
                                    'reserve.html', 
                                    student=student,
                                    user_in_login_page=True,
                                    action='Logout',
                                    labs=labs,
                                   )
         
        else:
            message = "Please login first."
            flash(message)
            return redirect(url_for('main.login'))
        
    except Exception as e:
        flash(str(e),'error')
        flash("Please try again")
        #session['student'] = None
        return redirect(url_for('main.login'))
    
@main.route('/records')
def records():
    """Record History Page"""
    global student
    try:

        if not session['student'] == None:
            if student == None:
                student_data = session.get('student')
                student = Student(**student_data)
            
            records = reservation.retrieve_sitinrecords()

            return render_template('records.html', student=student,user_in_login_page=True,action='Logout', records=records)

        else:
            message = "Please login first."
            flash(message)
            return redirect(url_for('main.login'))
        
    except Exception as e:
        flash(str(e),'error')
        flash("Please try again")
        #session['student'] = None
        return redirect(url_for('main.login'))

@main.route('/resources')
def resources():
    """Resources Page"""
    global student
    try:

        if not session['student'] == None:
            if student == None:
                student_data = session.get('student')
                student = Student(**student_data)

            return render_template('resources.html', student=student,
                                   user_in_login_page=True,
                                   action='Logout')

        else:
            message = "Please login first."
            flash(message)
            return redirect(url_for('main.login'))
        
    except Exception as e:
        flash(str(e),'error')
        flash("Please try again")
        #session['student'] = None
        return redirect(url_for('main.login'))

@main.route('/sessions')
def sessions():
    """Remaining Sessions Page"""
    global student
    try:

        if not session['student'] == None:
            if student == None:
                student_data = session.get('student')
                student = Student(**student_data)

            return render_template('sessions.html', student=student,
                                   user_in_login_page=True,
                                   action='Logout')

        else:
            message = "Please login first."
            flash(message)
            return redirect(url_for('main.login'))
        
    except Exception as e:
        flash(str(e),'error')
        flash("Please try again")
        #session['student'] = None
        return redirect(url_for('main.login'))


@main.route('/profilesettings')
def profilesettings():
    """Profile page."""
    global student
    try:

        if not session['student'] == None:
            if student == None:
                student_data = session.get('student')
                student = Student(**student_data)
            
            profileicons = student.profileicons

            return render_template(
                                    'profilesettings.html', 
                                    student=student,
                                    user_in_login_page=True,
                                    action='Logout',
                                    profileicons=profileicons,
                                    )
         
        else:
            message = "Please login first."
            flash(message)
            return redirect(url_for('main.login'))
        
    except Exception as e:
        flash(str(e),'error')
        flash("Please try again")
        return redirect(url_for('main.login'))      

@main.route('/logout')
def logout():
    """Logout page."""
    global student
    session['student'] = None
    student = None
    message = "You have been logged out."
    flash(message, 'success')
    return redirect(url_for('main.login'))

app/templates/student/dashboard_template.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon/favicon.ico') }}" />
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <title>CCSit-in System</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="min-h-screen flex flex-col">
  {% import 'components.html' as component %}
  <!-- Top Navigation Bar -->
  {{ component.navbar(user_in_login_page,action,student, is_admin) }}
  <!-- Flash Messages -->
  {{ component.flash_message() }}

  <div class="flex flex-1">
    <!-- Sidebar - removed fixed height -->
    <div class="w-64">
      <aside id="default-sidebar"
        class="top-0 left-0 z-40 w-64 transition-transform -translate-x-full sm:translate-x-0 h-full"
        aria-label="Sidebar">
        <div class="h-full px-3 py-4 overflow-y-auto bg-gray-50 dark:bg-gray-800">
          <ul class="space-y-2 font-medium">
            <li>
              <a href="{{ url_for('main.dashboard') }}"
                class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                <svg
                  class="w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
                  aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 21">
                  <path
                    d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z" />
                  <path
                    d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z" />
                </svg>
                <span class="ms-3">Dashboard</span>
              </a>
            </li>
            <li>
              <a href="{{ url_for('main.leaderboards') }}"
                class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                <svg
                  class="w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
                  aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 122.88 66.49" fill="currentColor">
                  <path fill-rule="evenodd"
                    d="M2.27,18.3H34.05a2.27,2.27,0,0,1,2.27,2.27V64.22a2.27,2.27,0,0,1-2.27,2.27H2.27A2.27,2.27,0,0,1,0,64.22V20.57A2.27,2.27,0,0,1,2.27,18.3ZM68.4,9.44V31H61V17.39l-4.52,1.8-2-5.3,7.66-4.45ZM26,49.45H11V43.81l2.84-2.75c.62-.57,1.21-1.13,1.77-1.7L17,38a7.69,7.69,0,0,0,1-1.24,3.52,3.52,0,0,0,.54-1,2.82,2.82,0,0,0,.09-.71,1.08,1.08,0,0,0-.5-1.08,4.54,4.54,0,0,0-1.73-.23,24,24,0,0,0-4.32.36l-.69.13L11,28.58a21.3,21.3,0,0,1,7.12-1.21A9.13,9.13,0,0,1,24,29.06a5.64,5.64,0,0,1,2.12,4.68,9.36,9.36,0,0,1-1,4.7A11.9,11.9,0,0,1,21.45,42l-2.19,1.54H26v5.9ZM103.1,37.19q4.82,0,7,1.37t2.18,4.85a6.81,6.81,0,0,1-.44,2.75,4.59,4.59,0,0,1-1.56,1.74A6.49,6.49,0,0,1,112,49.78a5.44,5.44,0,0,1,.52,2.64q0,4.09-2.13,5.65t-6.58,1.55A28.12,28.12,0,0,1,98,59l-1.08-.23L97.07,53q3.77.33,5.37.33a8,8,0,0,0,2.13-.18.76.76,0,0,0,.53-.79.91.91,0,0,0-.37-.83,2.48,2.48,0,0,0-1.37-.33H98.74v-5.8h4.32c1.18,0,1.77-.33,1.77-1s-.75-1-2.26-1c-1,0-2.53.08-4.52.23l-.85.07L97,38.14a26.29,26.29,0,0,1,6.06-1ZM45.55,0H77.33A2.27,2.27,0,0,1,79.6,2.27v62a2.27,2.27,0,0,1-2.27,2.27H45.55a2.27,2.27,0,0,1-2.27-2.27V2.27A2.27,2.27,0,0,1,45.55,0ZM88.83,30.35h31.78a2.28,2.28,0,0,1,2.27,2.27v31.6a2.27,2.27,0,0,1-2.27,2.27H88.83a2.27,2.27,0,0,1-2.27-2.27V32.62a2.27,2.27,0,0,1,2.27-2.27Z" />
                </svg>
                <span class="ms-3">Leaderboards</span>
              </a>
            </li>

            <li>
              <a href="{{ url_for('main.sitin') }}"
                class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                <svg
                  class="shrink-0 w-6 h-6 text-gray-500 dark:text-gray-400 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
                  aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                  viewBox="0 0 24 24">
                  <path fill-rule="evenodd"
                    d="M4 5.78571C4 4.80909 4.78639 4 5.77778 4H18.2222C19.2136 4 20 4.80909 20 5.78571V15H4V5.78571ZM12 12c0-.5523.4477-1 1-1h2c.5523 0 1 .4477 1 1s-.4477 1-1 1h-2c-.5523 0-1-.4477-1-1ZM8.27586 6.31035c.38089-.39993 1.01387-.41537 1.4138-.03449l2.62504 2.5c.1981.18875.3103.45047.3103.72414 0 .27368-.1122.5354-.3103.7241l-2.62504 2.5c-.39993.3809-1.03291.3655-1.4138-.0344-.38088-.4-.36544-1.033.03449-1.4138L10.175 9.5 8.31035 7.72414c-.39993-.38089-.41537-1.01386-.03449-1.41379Z"
                    clip-rule="evenodd" />
                  <path d="M2 17v1c0 1.1046.89543 2 2 2h16c1.1046 0 2-.8954 2-2v-1H2Z" />
                </svg>
                <span class="flex-1 ms-3 whitespace-nowrap">Laboratories</span>
              </a>
            </li>
            <li>
              <a href="{{ url_for('main.reserve') }}"
                class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                  class="shrink-0 w-6 h-6 text-gray-500 dark:text-gray-400 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
                  aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                  viewBox="0 0 24 24">
                  <path
                    d="M4 .5a.5.5 0 0 0-1 0V1H2a2 2 0 0 0-2 2v1h16V3a2 2 0 0 0-2-2h-1V.5a.5.5 0 0 0-1 0V1H4zM16 14V5H0v9a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2M8.5 8.5V10H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V11H6a.5.5 0 0 1 0-1h1.5V8.5a.5.5 0 0 1 1 0" />
                </svg>
                <span class="flex-1 ms-3 whitespace-nowrap">Reserve</span>
              </a>
            </li>
            <li>
              <a href="{{ url_for('main.resources') }}"
                class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                  class="bi bi-cloud-check-fill shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
                  viewBox="0 0 16 16">
                  <path
                    d="M8 2a5.53 5.53 0 0 0-3.594 1.342c-.766.66-1.321 1.52-1.464 2.383C1.266 6.095 0 7.555 0 9.318 0 11.366 1.708 13 3.781 13h8.906C14.502 13 16 11.57 16 9.773c0-1.636-1.242-2.969-2.834-3.194C12.923 3.999 10.69 2 8 2m2.354 4.854-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7 8.793l2.646-2.647a.5.5 0 0 1 .708.708" />
                </svg>
                <span class="flex-1 ms-3 whitespace-nowrap">Resources</span>
              </a>
            </li>
            <li>
              <a href="{{ url_for('main.sessions') }}"
                class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                  class="bi bi-alarm-fill text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
                  viewBox="0 0 16 16">
                  <path
                    d="M2.5 15a.5.5 0 1 1 0-1h1v-1a4.5 4.5 0 0 1 2.557-4.06c.29-.139.443-.377.443-.59v-.7c0-.213-.154-.451-.443-.59A4.5 4.5 0 0 1 3.5 3V2h-1a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1h-1v1a4.5 4.5 0 0 1-2.557 4.06c-.29.139-.443.377-.443.59v.7c0 .213.154.451.443.59A4.5 4.5 0 0 1 12.5 13v1h1a.5.5 0 0 1 0 1zm2-13v1c0 .537.12 1.045.337 1.5h6.326c.216-.455.337-.963.337-1.5V2zm3 6.35c0 .701-.478 1.236-1.011 1.492A3.5 3.5 0 0 0 4.5 13s.866-1.299 3-1.48zm1 0v3.17c2.134.181 3 1.48 3 1.48a3.5 3.5 0 0 0-1.989-3.158C8.978 9.586 8.5 9.052 8.5 8.351z" />
                </svg>
                <span class="flex-1 ms-3 whitespace-nowrap">Remaining Sessions</span>
              </a>
            </li>
            <li>
              <a href="{{ url_for('main.profilesettings') }}"
                class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                <svg
                  class="shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
                  aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                  viewBox="0 0 21 21">
                  <path stroke="currentColor" stroke-linecap="square" stroke-linejoin="round" stroke-width="2"
                    d="M10 19H5a1 1 0 0 1-1-1v-1a3 3 0 0 1 3-3h2m10 1a3 3 0 0 1-3 3m3-3a3 3 0 0 0-3-3m3 3h1m-4 3a3 3 0 0 1-3-3m3 3v1m-3-4a3 3 0 0 1 3-3m-3 3h-1m4-3v-1m-2.121 1.879-.707-.707m5.656 5.656-.707-.707m-4.242 0-.707.707m5.656-5.656-.707.707M12 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                </svg>
                <span class="flex-1 ms-3 whitespace-nowrap">Profile Settings</span>
              </a>
            </li>
          </ul>
        </div>
      </aside>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <div class="flex-1 min-h-0 overflow-auto">
      {% block content%}
      {% endblock %}
    </div>
  </div>

</body>

</html>

app/templates/student/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CCSit</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon/favicon.ico') }}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <style>
        @keyframes fadeIn {
            from {
                opacity: 0;
                transform: translateY(-20px);
            }

            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        .animate-fade-in {
            animation: fadeIn 0.5s ease-out;
        }

        body {
            font-family: 'Poppins', sans-serif;
        }
    </style>
</head>

<body class="bg-gray-100 font-sans"
    style="background-image: url('{{ url_for('static', filename='images/landingBG.jpg') }}'); background-size: cover; background-position: center;">
    {% import '/components.html' as component %}
    {{ component.navbar(user_in_login_page, action, user) }}
    <!-- Header Section -->
    {% if not user_in_login_page %}
    <header id="header-bg" class="flex items-center justify-center h-screen relative">
        <div class="absolute inset-0 bg-gradient-to-b from-black to-transparent opacity-70 filter brightness-75"></div>
        <div class="text-center relative z-10 animate-fade-in">
            <h1
                class="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 bg-clip-text">
                Simplify Your Workflow with CCSit</h1>
            <p class="text-l text-gray-200 mb-8">The ultimate tool for managing your projects efficiently and
                effectively.</p>
            <a href="{{ url_for('main.login') }}"
                class="bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 text-white px-8 py-3 rounded-lg text-lg hover:bg-gray-100 transition duration-300">Get
                Started</a>
        </div>
    </header>

    {% endif %}

    {{ component.flash_message() }}

    {% block content %}
    {% endblock %}

    {% if not user_in_login_page%}
    <!-- Additional Content Section -->
    <section class="py-16 bg-gray-50">
        <div class="container mx-auto px-6">
            <h2 class="text-3xl font-bold text-center text-gray-800 mb-8">Why Choose CCSit?</h2>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
                <div class="bg-white p-6 rounded-lg shadow-md animate-fade-in">
                    <h3 class="text-xl font-semibold text-gray-800 mb-4">Ease of Use</h3>
                    <p class="text-gray-600">Intuitive interface designed for seamless navigation and productivity.</p>
                </div>
                <div class="bg-white p-6 rounded-lg shadow-md animate-fade-in">
                    <h3 class="text-xl font-semibold text-gray-800 mb-4">Collaboration</h3>
                    <p class="text-gray-600">Work together with your team in real-time, no matter where you are.</p>
                </div>
                <div class="bg-white p-6 rounded-lg shadow-md animate-fade-in">
                    <h3 class="text-xl font-semibold text-gray-800 mb-4">Security</h3>
                    <p class="text-gray-600">Your data is safe with our top-notch security measures.</p>
                </div>
            </div>
        </div>
    </section>
    <!-- Footer -->
    <footer class="text-center py-6 bg-white border-t border-gray-200">
        <p class="text-gray-600">&copy; 2025 CCSit. All rights reserved.</p>
    </footer>
    {% endif %}

</body>

</html>

app/templates/student/records.html
{% extends 'dashboard_template.html' %} 
{% block content %}
<div class="bg-white shadow-md rounded-lg p-6 overflow-x-auto">
  <h3 class="text-xl font-semibold text-gray-700 mb-4">
    Sit-in Reservation Records
  </h3>
  <table class="min-w-full bg-white border-collapse border border-gray-300">
    <thead>
      <tr class="bg-gray-100">
        <th class="py-2 px-4 border text-center w-auto">Reservation ID</th>
        <th class="py-2 px-4 border text-center w-auto">Laboratory</th>
        <th class="py-2 px-4 border text-center w-auto">Student IDNO</th>
        <th class="py-2 px-4 border text-center w-auto">Name</th>
        <th class="py-2 px-4 border text-center w-auto">Status</th>
        <th class="py-2 px-4 border text-center w-auto">Sit-in Time</th>
        <th class="py-2 px-4 border text-center w-auto">Log-off Time</th>
        <th class="py-2 px-4 border text-center w-auto">Staff</th>
      </tr>
    </thead>
    <tbody>
        {% for record in records %}
        <tr class="border-b"></tr>
            <td class="py-2 px-4 border text-center">{{ record['reservation_id'] }}</td>
            <td class="py-2 px-4 border text-center">{{ record['lab_name'] }}</td>
            <td class="py-2 px-4 border text-center">{{ record['idno'] }}</td>
            <td class="py-2 px-4 border text-center">{{ record['firstname'] }}</td>
            <td class="py-2 px-4 border-b text-center">
            <span
                class="px-3 py-1 rounded-full text-sm font-semibold 
                {% if record['status'] == 'Completed' %}bg-gray-200
                {% elif record['status'] == 'Pending'%} bg-yellow-300
                {% elif record['status'] == 'Approved'%} bg-green-400
                {% elif record['status'] == 'Declined'%} bg-red-400 {% endif %}
                text-gray-700"
                >{{ record['status'] }}</span
            >
            </td>
            <td class="py-2 px-4 border text-center">{{ record['sitin_in'] }}</td>
            <td class="py-2 px-4 border text-center">{{ record['sitin_out'] }}</td>
            <td class="py-2 px-4 border text-center">{{ record['staff_idno'] }}</td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}